### PR TITLE
ZS_PR

### PR DESCRIPTION
**Pull request by zjschroeder**
Great work! I loved getting a sneak peek at some NLP in R!

### CODE REVIEW

**Comment by zjschroeder** [comment]
@datalorax

**Comment by zjschroeder** [comment]
(Also, my notes/comments are all in the code! I see that other folks added things in the comments, sorry for inconvenient formatting!)

**Comment by datalorax** [comment]
Thanks Zach, and no worries at all! I always review both so either way is fine. Really nice review!

**Comment by makwhit6** [comment]
Thank you for your thoughtful comments, Zach!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
